### ISSUE TITLE
Support for PIE dataset

### ISSUE THREAD

**Issue by Vaishnvi** [OSU-Haolin/Pedestrian_Crossing_Intention_Prediction#11]
Hi, Thanks for the great work, it's very helpful :) Can you please share an updated version that supports the PIE dataset?

**Comment by OSU-Haolin** [comment]
Now the PIE dataset is supported, and we will update the repo soon.

**Comment by dongfang-steven-yang** [comment]
PIE is now supported.

**Comment by hanzixuan316** [comment]
where can I get the PIE dataset？Please recommend me a internet adress

**Comment by OSU-Haolin** [comment]
Hi, I think it has the same webside link with JAAD, and you can search it on Google or their git repo.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: hanzixuan316 ***@***.***>
发送时间: Monday, November 25, 2024 2:04:47 PM
收件人: OSU-Haolin/Pedestrian_Crossing_Intention_Prediction ***@***.***>
抄送: Zhang, Haolin ***@***.***>; Comment ***@***.***>
主题: Re: [OSU-Haolin/Pedestrian_Crossing_Intention_Prediction] Support for PIE dataset (Issue #11)

where can I get the PIE dataset？Please recommend me a internet adress — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented. Message ID: <OSU-Haolin/Pedestrian_Crossing_Intention_Prediction/issues/11/2496938689@ github. com>


where can I get the PIE dataset？Please recommend me a internet adress
