### ISSUE TITLE
Cannot reproduce results in paper

### ISSUE THREAD

**Issue by dschoerk** [OSU-Haolin/Pedestrian_Crossing_Intention_Prediction#6]
hi, i'm trying to reproduce the results reported in your paper. kindly let me know how to train the best performing as shown in Table1: 
![grafik](https://user-images.githubusercontent.com/913265/120278845-1198e000-c2b6-11eb-9b9c-8facbe5dde78.png)

it appears to me that the correct config for this would be MASK_PCPA_jaad_2d.yaml, is that correct?
`python train_test.py -c config_files/ours/MASK_PCPA_jaad_2d.yaml`

my result for this model are somewhat far off from what's reported in table 1
for jaad_beh:
results:
  acc: 0.580542264752791
  auc: 0.5232582837723024
  f1: 0.691435275713727
  precision: 0.6405797101449275
  recall: 0.7510620220900595

for jaad_all:
results:
  acc: 0.7874331550802139
  auc: 0.8035675530169841
  f1: 0.5767524401064773
  precision: 0.4423774954627949
  recall: 0.8283772302463891

**Comment by OSU-Haolin** [comment]
Hi, you can try some training strategies to help improve the results, such as cross-validation, early stopping, etc.
I will let you know when I upload the pre-trained models to Google Drive, and you can try our pre-trained models to reproduce the results in paper.

**Comment by OSU-Haolin** [comment]
Now pre-trained models were uploaded and you can see links in README.
It is better to try a larger dataset such as the PIE dataset for achieving more reliable results.

**Comment by dschoerk** [comment]
> you can try some training strategies to help improve the results, such as cross-validation, early stopping, etc.

did you apply any additional techniques to create your final model which aren't present in the code or configs currently? according to the paper: "all  models  were  trained  using  the  bench-mark implementation released with PCPA model [10]"

> Now pre-trained models were uploaded and you can see links in README.

thanks, i've sent a request to access it. to validate the results in the paper and for comparison with future methods, i'd still prefer to be able to train the model myself.

**Comment by OSU-Haolin** [comment]
> > you can try some training strategies to help improve the results, such as cross-validation, early stopping, etc.
> 
> did you apply any additional techniques to create your final model which aren't present in the code or configs currently? according to the paper: "all models were trained using the bench-mark implementation released with PCPA model [10]"
> 
> > Now pre-trained models were uploaded and you can see links in README.
> 
> thanks, i've sent a request to access it. to validate the results in the paper and for comparison with future methods, i'd still prefer to be able to train the model myself.

We tried the PCPA model in their own benchmark and got different results compared to their paper. So in our paper and our project, we keep the same configuration and retrained all models. The performance shown in the paper is from the best model we trained by using the JAAD dataset. Since there are not too many data samples in the JAAD dataset, the performance of trained models is not stable enough, and it is normal for some fluctuations in the result. For future comparison, I think that there are some potential options for you as follows. You can download our pre-trained models, train your own model, and then compare your model's performance with ours. Or you can retrain all given models as well as your own model, calculate the average performance or choose the best performance as result. Or you can try the larger dataset such as the PIE dataset, which would give you more stable results (PIE pose data can be downloaded from https://github.com/ykotseruba/PedestrianActionBenchmark/tree/main/data/features/pie/poses).

**Comment by dschoerk** [comment]
thank you for you answers and suggestions!
